_wandb:
    value:
        cli_version: 0.18.7
        m:
            - "1": test_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": val_loss_centroid
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_loss_mult
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss_nH
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test_loss_nH
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test_loss_width
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test_loss_mult
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss_centroid
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss_mult
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_loss
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_loss_nH
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss_width
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": test_loss_centroid
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_loss_width
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 9
                - 55
                - 77
                - 103
            "2":
                - 1
                - 9
                - 55
                - 77
                - 103
            "3":
                - 7
                - 13
                - 23
                - 55
                - 66
            "4": 3.10.13
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
hidden_dim:
    value: 32
in_dim:
    value: 7
mult_class_num:
    value: 40
nH_class_num:
    value: 14
num_heads:
    value: 2
num_layers:
    value: 4
